"""Initialize a project .agent runtime without overwriting existing state."""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

from runtime_utils import agent_path, empty_state, write_json_atomic, write_text_atomic


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    args = parser.parse_args()
    root = agent_path(args.project_root)
    staging: Path | None = None
    try:
        project_root = root.parent
        project_root.mkdir(parents=True, exist_ok=True)
        if root.exists() or root.is_symlink():
            print(f"REFUSED: runtime already exists at {root}", file=sys.stderr)
            return 2

        # Build the complete runtime beside .agent, then publish it in one rename.
        staging = Path(tempfile.mkdtemp(prefix=f".{root.name}.init-", dir=project_root))
        runtime = staging / "runtime"
        for relative in (
            "runtime",
            "runtime/staging",
            "runtime/transactions",
            "work",
            "checkpoints/global",
            "checkpoints/agents",
            "locks/tasks",
            "locks/files",
            "locks/resources",
            "recovery",
            "logs/executors",
            "logs/reviewers",
            "logs/harness",
        ):
            (staging / relative).mkdir(parents=True, exist_ok=True)
        write_json_atomic(runtime / "state.json", empty_state())
        write_text_atomic(runtime / "events.jsonl", "")
        write_json_atomic(runtime / "agents.json", {"schema_version": 1, "agents": []})
        write_json_atomic(runtime / "queue.json", {"schema_version": 1, "queue_id": "RUNTIME-QUEUE", "revision": 0, "tasks": [], "task_states": [], "dispatches": [], "locks": []})
        write_json_atomic(runtime / "graph.json", {"schema_version": 1, "graph_id": "RUNTIME-GRAPH", "revision": 0, "nodes": [], "edges": []})
        write_json_atomic(staging / "recovery" / "recovery-state.json", {"schema_version": 1, "classification": "NONE"})
        write_json_atomic(staging / "recovery" / "stale-runs.json", {"schema_version": 1, "runs": []})
        write_text_atomic(staging / "recovery" / "recovery-log.jsonl", "")
        write_text_atomic(
            staging / "checklist.md",
            "# Agentic Task Checklist\n\n<!-- Generated by agentic-state-tools. Do not edit as a source of truth. -->\n\n",
        )
        staging.rename(root)
    except FileExistsError:
        print(f"REFUSED: runtime already exists at {root}", file=sys.stderr)
        return 2
    except (OSError, ValueError) as exc:
        print(f"INIT_FAILED: {exc}", file=sys.stderr)
        return 1
    finally:
        if staging is not None and staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
    print(f"INITIALIZED: {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
