"""Render the user-facing checklist from canonical task state and reviews."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from runtime_utils import (
    RuntimeLockedError,
    RuntimeNotInitializedError,
    ensure_runtime_initialized,
    read_object,
    runtime_lock,
    utc_now,
    write_text_atomic,
)


PASS_VERDICTS = {"PASS", "PASSED", "ACCEPTED"}


def review_passed(work_dir: Path) -> bool:
    review_path = work_dir / "review.json"
    if not review_path.is_file():
        return False
    review = read_object(review_path)
    return str(review.get("verdict", "")).upper() in PASS_VERDICTS


def render_checklist_for_root(root: Path) -> Path:
    rows: list[str] = []
    work_root = root / "work"
    for task_file in sorted(work_root.glob("*/task-state.json")):
        task_state = read_object(task_file)
        task_id = task_state.get("task_id")
        status = str(task_state.get("status", "")).upper()
        if not isinstance(task_id, str) or not task_id or not status:
            raise ValueError(f"invalid task state: {task_file}")
        title = str(task_state.get("title") or task_state.get("objective") or task_id)
        checked = status == "ACCEPTED" and review_passed(task_file.parent)
        rows.append(f"- [{'x' if checked else ' '}] {task_id} - {title} ({status})")

    content = [
        "# Agentic Task Checklist",
        "",
        f"<!-- Generated by agentic-state-tools at {utc_now()}. Do not edit as a source of truth. -->",
        "",
        *(rows or ["- [ ] No task state has been generated yet."]),
        "",
    ]
    target = root / "checklist.md"
    write_text_atomic(target, "\n".join(content))
    return target


def render_checklist(project_root: str, *, acquire_lock: bool = True) -> Path:
    if acquire_lock:
        with runtime_lock(project_root) as root:
            return render_checklist_for_root(root)
    return render_checklist_for_root(ensure_runtime_initialized(project_root))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    args = parser.parse_args()
    try:
        target = render_checklist(args.project_root)
    except RuntimeNotInitializedError as exc:
        print(f"CHECKLIST_BLOCKED: {exc}", file=sys.stderr)
        return 2
    except (RuntimeLockedError, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"CHECKLIST_FAILED: {exc}", file=sys.stderr)
        return 1
    print(f"CHECKLIST_RENDERED: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
